sources:
  - name: s1
    database: dev_db
    schema: bronze
    tables:
      - name: t_ticket_info
      - name: customer
      - name: t_customer
      - name: s_emp
      - name: customers
      - name: emp
      - name: orders
      - name: tgt_emp
      - name: payment	
      - name: t_claims
        identifier: T_CLAIMS
      - name: t_claim_diagnosis
        identifier: T_CLAIM_DIAGNOSIS
      - name: t_claim_events
        identifier: T_CLAIM_EVENTS      